// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title DataIntegrityRegistry
 * @dev Implements a tamper-proof registry for AI dataset hashes on Polygon.
 */
contract DataIntegrityRegistry {
    address public owner;

    // Struct to hold metadata about the registered data
    struct DataRecord {
        bytes32 dataHash;      // The SHA-256 fingerprint
        uint256 timestamp;     // When it was anchored on-chain
        address registeredBy;  // The backend wallet address
    }

    // Mapping from a unique Data ID (e.g., "dataset_v1_2026") to its Record
    mapping(string => DataRecord) private registry;

    event DataAnchored(string indexed dataId, bytes32 dataHash, uint256 timestamp);

    constructor() {
        owner = msg.sender;
    }

    modifier onlyOwner() {
        require(msg.sender == owner, "Only the authorized backend can anchor data");
        _;
    }

    /**
     * @notice Anchors a new data hash to the blockchain.
     * @param _dataId A unique identifier for the dataset.
     * @param _dataHash The SHA-256 hash of the dataset.
     */
    function anchorData(string calldata _dataId, bytes32 _dataHash) external onlyOwner {
        require(registry[_dataId].timestamp == 0, "This Data ID has already been anchored");

        registry[_dataId] = DataRecord({
            dataHash: _dataHash,
            timestamp: block.timestamp,
            registeredBy: msg.sender
        });

        emit DataAnchored(_dataId, _dataHash, block.timestamp);
    }

    /**
     * @notice Verifies if the provided hash matches the one stored on-chain.
     * @param _dataId The unique identifier to check.
     * @param _observedHash The hash generated by the AI agent during runtime.
     * @return isValid True if the data has not been tampered with.
     */
    function verifyIntegrity(string calldata _dataId, bytes32 _observedHash) external view returns (bool isValid) {
        if (registry[_dataId].timestamp == 0) return false;
        return (registry[_dataId].dataHash == _observedHash);
    }

    /**
     * @notice Helper to fetch full record details
     */
    function getRecord(string calldata _dataId) external view returns (bytes32, uint256, address) {
        DataRecord memory record = registry[_dataId];
        return (record.dataHash, record.timestamp, record.registeredBy);
    }
}
